// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQTtS3pBNBWgsrRg62JuQq1h-8zI_wx20',
    appId: '1:194766899852:web:514763ad33797b6d26c9a9',
    messagingSenderId: '194766899852',
    projectId: 'light-60803',
    authDomain: 'light-60803.firebaseapp.com',
    storageBucket: 'light-60803.appspot.com',
    measurementId: 'G-8PFSX6KWBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHcobyOXVOgjNAZoIUOC_TuNvnEoJxNmo',
    appId: '1:194766899852:android:d83a245c8d9389b926c9a9',
    messagingSenderId: '194766899852',
    projectId: 'light-60803',
    storageBucket: 'light-60803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrwmW5ScELiln0jfrDhDi7m30MatqONo',
    appId: '1:194766899852:ios:884553c0793d42f826c9a9',
    messagingSenderId: '194766899852',
    projectId: 'light-60803',
    storageBucket: 'light-60803.appspot.com',
    iosClientId: '194766899852-6cqbmk6ui3ofu7nms3g6vmpeqpjspv53.apps.googleusercontent.com',
    iosBundleId: 'com.example.proOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrwmW5ScELiln0jfrDhDi7m30MatqONo',
    appId: '1:194766899852:ios:731b64b3b5814f6926c9a9',
    messagingSenderId: '194766899852',
    projectId: 'light-60803',
    storageBucket: 'light-60803.appspot.com',
    iosClientId: '194766899852-baku9d7hrpmi012puipkus03d7ncugae.apps.googleusercontent.com',
    iosBundleId: 'com.example.proOne.RunnerTests',
  );
}
